version: '3.9'

services:
  frontend:
    build:
      context: frontend
      dockerfile: .docker/Dockerfile
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calendar_frontend.rule=Host(`calendar.hilbertsen.com`)"
      - "traefik.http.services.calendar_frontend.loadbalancer.server.port=80"

  server:
    build:
      context: server
      dockerfile: .docker/api/Dockerfile
    restart: always
    environment:
      - DATABASE_PASSWORD=$CALENDAR_DATABASE_PASSWORD
      - SECRET_KEY=$CALENDAR_SECRET_KEY
      - APP_ENVIRONMENT=Td
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calendar_server.rule=Host(`server.calendar.hilbertsen.com`)"
      - "traefik.http.services.calendar_server.loadbalancer.server.port=80"

  postgres:
    image: postgres:15-alpine
    shm_size: 1g
    restart: always
    environment:
      - POSTGRES_PASSWORD=$CALENDAR_DATABASE_PASSWORD
    volumes:
      - ./db:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432

networks:
  default:
    name: calendar_network
