version: '3.5'
services:
  frontend:
    build:
      context: frontend
      dockerfile: .docker/Dockerfile
    restart: always
    ports:
      - "12000:80"

  server:
    build:
      context: Server
      dockerfile: .docker/Dockerfile
    restart: always
    environment:
      DATABASE_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - type: bind
        source: /etc/letsencrypt/live/calendar.hilbertsen.com
        target: /https/live/calendar.hilbertsen.com
      - type: bind
        source: /etc/letsencrypt/archive/calendar.hilbertsen.com
        target: /https/archive/calendar.hilbertsen.com
    ports:
      - "5200:5100"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    user: root
    environment:
      SA_PASSWORD: $DATABASE_PASSWORD
      ACCEPT_EULA: "Y"
    volumes:
      - ./db:/var/opt/mssql/data


networks:
  default:
    name: calendar_network
