version: '3.9'

services:
  frontend:
    build:
      context: frontend
      dockerfile: .docker/Dockerfile
      args:
        - APP_ENVIRONMENT=avskjerming
    restart: always
    ports:
      - 11000:80

  server:
    build:
      context: server
      dockerfile: .docker/api/Dockerfile
    restart: always
    environment:
      - PGPASSWORD=$PGPASSWORD
      - APP_ENVIRONMENT=Avskjerming
    ports:
      - 5000:5000

  postgres:
    image: postgres:15-alpine
    shm_size: 1g
    restart: always
    environment:
      - POSTGRES_PASSWORD=$PGPASSWORD
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  default:
    name: calendar_network
