version: '3.5'
services:
  frontend:
    build:
      context: frontend
      dockerfile: .docker/Dockerfile
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calendar_frontend.rule=Host(`calendar.hilbertsen.com`)"
      - "traefik.http.services.calendar_frontend.loadbalancer.server.port=80"

  server:
    build:
      context: server
      dockerfile: .docker/Dockerfile
    restart: always
    environment:
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      SERVER_SECRET: $SERVER_SECRET
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calendar_server.rule=Host(`server.calendar.hilbertsen.com`)"
      - "traefik.http.services.calendar_server.loadbalancer.server.port=80"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - ./db:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    # ports:
    #   - '5432:5432'


networks:
  default:
    name: calendar_network
