version: '3.5'
services:
  frontend:
    build:
      context: frontend
      dockerfile: .docker/Dockerfile
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    ports:
      - "12000:80"

  server:
    build:
      context: server
      dockerfile: .docker/Dockerfile
    restart: always
    environment:
      DATABASE_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - type: bind
        source: /etc/letsencrypt/live/calendar.hilbertsen.com
        target: /https/live/calendar.hilbertsen.com
      - type: bind
        source: /etc/letsencrypt/archive/calendar.hilbertsen.com
        target: /https/archive/calendar.hilbertsen.com
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    ports:
      - "5200:5200"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - ./db:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    # ports:
    #   - '5432:5432'


networks:
  default:
    name: calendar_network
