version: '3.9'

services:
  frontend:
    build:
      context: frontend
      dockerfile: .docker/Dockerfile
      args:
        - APP_ENVIRONMENT=development
    ports:
      - 11000:80

  server:
    build:
      context: server
      dockerfile: .docker/api/Dockerfile
    environment:
      - APP_ENVIRONMENT=Local
    ports:
      - 5000:5000

  postgres:
    image: postgres:15-alpine
    shm_size: 1g
    restart: always
    environment:
      - POSTGRES_PASSWORD=test123
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 6432:5432

  postgres-test:
    image: calendar/postgres-test
    build:
      context: server
      dockerfile: .docker/postgres-test/Dockerfile
    environment:
      - POSTGRES_PASSWORD=test123
    ports:
      - 6433:5432

  postgres-check:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=test123
    ports:
      - 6434:5432


networks:
  default:
    name: calendar_network
