version: '3.9'

services:
  frontend:
    build:
      context: frontend
      dockerfile: .docker/Dockerfile
    ports:
      - 11000:80

  server:
    build:
      context: server
      dockerfile: .docker/Dockerfile
    environment:
      - DATABASE_PASSWORD=test123
      - APP_ENVIRONMENT=Local
    ports:
      - 5000:5000

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=test123
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  postgres-test:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=test123
    ports:
      - 5433:5432

  postgres-check:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=test123
    ports:
      - 5434:5432


networks:
  default:
    name: calendar_network
